# -*- coding: utf-8 -*-
""" --------------------------------------------------------------------------------------------------------------
#   Code created by: Rafaël Sanvicente (rafael.sanvicente.116@cranfield.ac.uk) for the turbulence modeling assignment
#                   part of the MSc in CFD course.
#
#   Plots the data of the .out files generated by the exported report files of Fluent calculations, helps monitor quantities of interest. 
#   
#   LICENCE:
#   This script is free of use for any student / research related work, NON-COMMERCIAL USE ONLY.
#   If you are brought to use this project, the author kindly asks for this work to be referenced.
#   Feel free to improve this file as you wish and implement further capabilities 
#
#   Created: 01/2024
#   V1.0
 ---------------------------------------------------------------------------------------------------------------- """


import matplotlib.pyplot as plt
import pandas as pd

# Chemin du fichier
file_path = 'p_dyn-rfile'

# Lire le fichier en sautant les lignes non nécessaires
# Les données commencent à la 4ème ligne (index 3 en Python)
data = pd.read_csv(file_path, delim_whitespace=True, skiprows=3, names=["Iteration", "p_dyn"])

# Tracer les données
plt.plot(data["Iteration"], data["p_dyn"])
plt.xlabel("Iteration")
plt.ylabel("p_dyn")
plt.title("Dynamique de pression au fil des itérations")
plt.grid(True)
plt.show()